### PR TITLE
Example of selecting visability of ifc elements from a checked @widge…

### PR DESCRIPTION
**Pull request by tonyk24**
…tjs/tree tree view

### CODE REVIEW

**Comment by agviegas** [comment]
Hey @tonyk24 this is fantastic! Just one question, when I try to rebuild it, I don't know where you are importing `@widgetjs` from. Is that an npm module? Also, if you are willing to write a short tutorial for this in our docs, we could create a $100 bounty, so you would get paid for it. Cheers!

**Comment by agviegas** [comment]
Hey @tonyk24 if I try to clone your branch and rebuild, I get this error. Does it work at your end? Otherwise, I'll close this. Cheers!

image

**Comment by tonyk24** [comment]
Yeah sorry. Don't think it is working. I renamed one part wrongly. I got busy with some other stuff so you can close it.

**Comment by agviegas** [comment]
No worries @tonyk24 ! We are now paying contributions via [bounties](https://bounties.ifcjs.io/). If you'd like to contribute, let us know so we can pay you for your time. Cheers!

**Pull request closed without merging**
