### PR TITLE
Fixed some docs that might confuse new comers

### PR DESCRIPTION
**Pull request by pkpndy**
fixed some docs to understand easily

### CODE REVIEW

**Comment by agviegas** [comment]
Hi, as far as I can see, you only added 2 new lines in 2 sentences. I'm sorry, but I can't see the added value of this? 🤔

**Comment by pkpndy** [comment]
> Hi, as far as I can see, you only added 2 new lines in 2 sentences. I'm sorry, but I can't see the added value of this? 

The previous explanation would have confused new comers. So I thought why not clearly differentiate it.

**Comment by agviegas** [comment]
I'm sorry, but I don't see the value in adding two new lines. If you are willing to contribute, you can check out our [bounty page](https://bounties.ifcjs.io/) and even get paid for it. Cheers!

**Comment by pkpndy** [comment]
Sure and thanks.

**Pull request closed without merging**
